name = "tsukutta-api"
main = "src/index.ts"
compatibility_date = "2025-02-24"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "family-cook-log"
database_id = "4b235573-b4ff-40f1-9818-7926cee421d5"
migrations_dir = "migrations"

[vars]
CORS_ALLOWED_ORIGINS = "https://tsukutta-web.deeev-work.workers.dev"
APP_BASE_URL = "https://tsukutta-web.deeev-work.workers.dev"
SESSION_COOKIE_NAME = "tsukutta_session"
CLOUDINARY_CLOUD_NAME = "bpwmajyk"
